# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-Reuse
version:      0.33
version_from: Reuse.pm
installdirs:  site
requires:
    AutoLoader:                    0
    Carp:                          0
    Compress::Zlib:                0
    Data::Dumper:                  0
    Digest::MD5:                   0
    Exporter:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
